# Generated by Django 4.2.20 on 2025-03-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=20)),
                ('employeename', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee-images')),
            ],
        ),
    ]
