# Generated by Django 4.2.20 on 2025-03-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
